name: My main test action
run-name: My main test action

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: elizabethtl/hello-world-composite-action@v1
        with:
          who-to-greet: 'Mona the Octocat'

      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
          
      - name: Get branch names.
        id: branch-names-8
        uses: tj-actions/branch-names@v8

      - name: Get branch names.
        id: branch-names-8-0-2
        uses: tj-actions/branch-names@v8.0.2

        
