name: My main test action
run-name: My main test action

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: elizabethtl/hello-world-composite-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8
      - name: Output branch names.
        run: |
          echo "Running on default: ${{ steps.branch-names.outputs.current_branch }}" 
          echo "Base branch: ${{ steps.branch-names.outputs.base_ref_branch }}"
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
